print('Mam na imię Karolina')

print('Mam na imię Karolina')
print('Mam na imię Karolina')
print('Mam na imię Karolina')
print('Mam na imię Karolina')
print('Mam na imię Karolina')
print('Mam na imię Karolina')
print('Mam na imię Karolina')
print('Mam na imię Karolina')
print('Mam na imię Karolina')
